PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>

SELECT distinct ?subject_id ?object_id WHERE 
{
  ?subject oio:hasDbXref ?object  .
  ?subject <http://scdontology.h3abionet.org/ontology/SCDO_1000288> ?sufficient .
  FILTER (str(?sufficient) = "Sufficient")
  FILTER (!regex(str(?object),"^AERO"))
  FILTER (!regex(str(?object),"^APAONTO"))
  FILTER (!regex(str(?object),"^BAO"))
  FILTER (!regex(str(?object),"^CRISP"))
  FILTER (!regex(str(?object),"^CSP"))
  FILTER (!regex(str(?object),"^EDDA"))
  FILTER (!regex(str(?object),"^EFO"))
  FILTER (!regex(str(?object),"^ERO"))
  FILTER (!regex(str(?object),"^FaBiO"))
  FILTER (!regex(str(?object),"^FYPO"))
  FILTER (!regex(str(?object),"^ICD10CM"))
  FILTER (!regex(str(?object),"^IDODEN"))
  FILTER (!regex(str(?object),"^MESH"))
  FILTER (!regex(str(?object),"^MMO"))
  FILTER (!regex(str(?object),"^NPO"))
  FILTER (!regex(str(?object),"^OAE"))
  FILTER (!regex(str(?object),"^LNC"))
  FILTER (!regex(str(?object),"^ORPHA"))
  FILTER (!regex(str(?object),"^phenX"))
  FILTER (!regex(str(?object),"^SIO"))
  FILTER (!regex(str(?object),"^sio"))
  FILTER (!regex(str(?object),"^VSO"))
  FILTER(isIRI(?subject) && regex(str(?subject), "http[:][/][/]scdontology[.]h3abionet[.]org[/]ontology[/]SCDO[_]"))
  BIND(REPLACE(STR(?subject), "http[:][/][/]scdontology[.]h3abionet[.]org[/]ontology[/]SCDO[_]", "SCDO:", "i") AS ?subject_id)
  BIND(IF(regex(str(?object), "http[:][/][/]www[.]ebi[.]ac[.]uk[/]efo[/]EFO[_]")
				|| regex(str(?object), "http[:][/][/]purl[.]obolibrary[.]org[/]obo[/]")
				|| regex(str(?object), "http[:][/][/]www[.]orpha.net[/]ORDO[/]"),
		REPLACE(
			REPLACE(STR(?object), "http[:][/][/]purl[.]obolibrary[.]org[/]obo[/]|http[:][/][/]www[.]ebi[.]ac[.]uk[/]efo[/]|http[:][/][/]www[.]orpha.net[/]ORDO[/]", "", "i"),
		"[_]", ":", "i")
		,?object) AS ?object_id)
}